[2023-10-11T17:04:43.314+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_etl.raw manual__2023-10-11T16:54:38.637745+00:00 [queued]>
[2023-10-11T17:04:43.319+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_etl.raw manual__2023-10-11T16:54:38.637745+00:00 [queued]>
[2023-10-11T17:04:43.320+0000] {taskinstance.py:1359} INFO - Starting attempt 3 of 3
[2023-10-11T17:04:43.330+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): raw> on 2023-10-11 16:54:38.637745+00:00
[2023-10-11T17:04:43.335+0000] {standard_task_runner.py:57} INFO - Started process 1173 to run task
[2023-10-11T17:04:43.338+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_etl', 'raw', 'manual__2023-10-11T16:54:38.637745+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_etl.py', '--cfg-path', '/tmp/tmpfs6qsx5v']
[2023-10-11T17:04:43.341+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask raw
[2023-10-11T17:04:43.381+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_etl.raw manual__2023-10-11T16:54:38.637745+00:00 [running]> on host 8294e6c9f0c9
[2023-10-11T17:04:43.441+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wikipedia_etl' AIRFLOW_CTX_TASK_ID='raw' AIRFLOW_CTX_EXECUTION_DATE='2023-10-11T16:54:38.637745+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-11T16:54:38.637745+00:00'
[2023-10-11T17:04:43.443+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/wikipedia_etl.py", line 38, in raw
    processing_date = {{ ds }}
NameError: name 'ds' is not defined
[2023-10-11T17:04:43.449+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=wikipedia_etl, task_id=raw, execution_date=20231011T165438, start_date=20231011T170443, end_date=20231011T170443
[2023-10-11T17:04:43.459+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task raw (name 'ds' is not defined; 1173)
[2023-10-11T17:04:43.471+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-11T17:04:43.487+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
