[2023-10-11T17:57:59.106+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_etl.raw manual__2023-10-11T17:57:58.061220+00:00 [queued]>
[2023-10-11T17:57:59.114+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_etl.raw manual__2023-10-11T17:57:58.061220+00:00 [queued]>
[2023-10-11T17:57:59.114+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2023-10-11T17:57:59.137+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): raw> on 2023-10-11 17:57:58.061220+00:00
[2023-10-11T17:57:59.146+0000] {standard_task_runner.py:57} INFO - Started process 2640 to run task
[2023-10-11T17:57:59.150+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_etl', 'raw', 'manual__2023-10-11T17:57:58.061220+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_etl.py', '--cfg-path', '/tmp/tmpdcaz90jn']
[2023-10-11T17:57:59.153+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask raw
[2023-10-11T17:57:59.252+0000] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_etl.raw manual__2023-10-11T17:57:58.061220+00:00 [running]> on host 8294e6c9f0c9
[2023-10-11T17:57:59.318+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wikipedia_etl' AIRFLOW_CTX_TASK_ID='raw' AIRFLOW_CTX_EXECUTION_DATE='2023-10-11T17:57:58.061220+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-11T17:57:58.061220+00:00'
[2023-10-11T17:57:59.320+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 190, in execute
    self.op_kwargs = self.determine_kwargs(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 201, in determine_kwargs
    return KeywordParameters.determine(self.python_callable, self.op_args, context).unpacking()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 163, in determine
    raise ValueError(f"The key {name!r} in args is a part of kwargs and therefore reserved.")
ValueError: The key 'ds' in args is a part of kwargs and therefore reserved.
[2023-10-11T17:57:59.328+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=wikipedia_etl, task_id=raw, execution_date=20231011T175758, start_date=20231011T175759, end_date=20231011T175759
[2023-10-11T17:57:59.339+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task raw (The key 'ds' in args is a part of kwargs and therefore reserved.; 2640)
[2023-10-11T17:57:59.362+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-11T17:57:59.381+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
